config/routes.rb
SaintsAlum::Application.routes.draw do  
  
  root to: "static_pages#home"

  resources :users do 
    member do 
      get :following, :followers 
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :edit]
  resources :relationships, only: [:create, :destroy, :edit]
  
  match "/about",   to: "static_pages#about" 
  match "/contact", to: "static_pages#contact" 
  match "/help",    to: "static_pages#help"

  match "/signup",    to: "users#new"
  match "/edit_user", to: "users#edit"

  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete 

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="jumbotron">
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user, ""), feed_item.user %>

  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user, id: "dark-link" %><br />
  </span>
  <span class="title"><%= feed_item.title %></span>
  <span class="content">
    <%= feed_item.content.html_safe %><br />
    <% if feed_item.image? %>
    <div class="image">
      <%= image_tag feed_item.image_url(:thumb).to_s %>
    </div>
    <% else %>
      <p></p>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago
  </span>
  <% if current_user?(feed_item.user) %>
  <small>
    <%= link_to "delete", feed_item, method: :delete,
                      data: { confirm: "Are you sure?" }, 
                      title: feed_item.content, id: "dark-link" %>
  </small>
  <% end %>
</li>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: {multipart: true})  do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="form-horizontal" id="micro-input" role="form">
    <%= f.text_area :title, placeholder: "Title", class: "form-control", rows: "1" %>      
    <%= f.text_area :content, placeholder: "Compose new post...", class: "form-control", rows: "5" %>
  </div>
  <p>
    <%= f.file_field :image, class: "form-control" %>

    <%= f.label :remote_image_url, "or image URL" %><br />
    <%= f.text_field :remote_image_url, class: "form-control", rows: "1"  %>
  </p>
  <div id="button">
   <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <a href="<%=following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
      </strong>
      following
  </a>
  <a href="<%=followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
      </strong>
      followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, "" %>
</a>

<h1><%= current_user.name %></h1>

<%= current_user.year %>


<span>
  <%= link_to "view my profile", current_user, class: "gravatar-micro" %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "posts") %>
</span>