config/routes.rb
SaintsAlum::Application.routes.draw do  
  
  root to: "static_pages#home"

  resources :users do 
    member do 
      get :following, :followers 
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :edit]
  resources :relationships, only: [:create, :destroy, :edit]
  
  match "/about",   to: "static_pages#about" 
  match "/contact", to: "static_pages#contact" 
  match "/help",    to: "static_pages#help"

  match "/signup",    to: "users#new"
  match "/edit_user", to: "users#edit"

  match "/signin",  to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by: <%= link_to "Colin B. Stodd", "https://github.com/cbstodd" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SaintsAlum.com", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path, id: "header_links" %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path, id: "header_links" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-target="#" role="menu" id="header_links">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu " id="bs-example-navbar-collapse-1">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path, id: "header_links" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>